-- ============================================================
-- CREATE CLINICS TABLE
-- Matches the existing AppointDent schema
-- ============================================================

CREATE TABLE IF NOT EXISTS public.clinics (
  id                      BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name                    TEXT NOT NULL,
  address                 TEXT NOT NULL,
  latitude                NUMERIC(9,6),
  longitude               NUMERIC(9,6),
  phone                   TEXT,
  email                   TEXT,
  max_appointments_per_day INT DEFAULT 20,
  is_active               BOOLEAN DEFAULT true,
  created_at              TIMESTAMPTZ DEFAULT now(),
  updated_at              TIMESTAMPTZ DEFAULT now()
);

-- Create indexes for common queries
CREATE INDEX IF NOT EXISTS idx_clinics_is_active ON public.clinics(is_active);
CREATE INDEX IF NOT EXISTS idx_clinics_created_at ON public.clinics(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_clinics_email ON public.clinics(email);

-- Enable RLS
ALTER TABLE public.clinics ENABLE ROW LEVEL SECURITY;

-- Create RLS policies for superadmin access
CREATE POLICY "Allow superadmin to read clinics" 
  ON public.clinics 
  FOR SELECT 
  USING (true);

CREATE POLICY "Allow superadmin to insert clinics" 
  ON public.clinics 
  FOR INSERT 
  WITH CHECK (true);

CREATE POLICY "Allow superadmin to update clinics" 
  ON public.clinics 
  FOR UPDATE 
  USING (true);

CREATE POLICY "Allow superadmin to delete clinics" 
  ON public.clinics 
  FOR DELETE 
  USING (true);

