-- ============================================================
-- 0. THE "NUKE & PAVE" CLEANUP
-- Forcefully removes all old tables, functions, and types
-- so you don't get "already exists" or "return type" errors.
-- ============================================================
DROP FUNCTION IF EXISTS public.auth_role() CASCADE;
DROP FUNCTION IF EXISTS public.auth_clinic_id() CASCADE;

DROP TABLE IF EXISTS
  public.users, public.clinics, public.clinic_operating_hours, public.clinic_hmo,
  public.clinic_gallery, public.clinic_holidays, public.clinic_staff, public.dentists,
  public.dentist_availability, public.dentist_blocked_slots, public.services, public.products,
  public.patients, public.informed_consent, public.patient_medical_history, public.appointments,
  public.appointment_logs, public.dental_charts, public.tooth_conditions, public.periodontal_screenings,
  public.tmj_assessments, public.oral_surgery_records, public.prescriptions, public.clinical_assessments,
  public.treatment_history, public.follow_up_schedules, public.transactions, public.transaction_items,
  public.inventory_items, public.inventory_logs, public.notifications, public.feedback
CASCADE;

DROP TYPE IF EXISTS user_role CASCADE;
DROP TYPE IF EXISTS appointment_status CASCADE;
DROP TYPE IF EXISTS payment_method CASCADE;
DROP TYPE IF EXISTS payment_status CASCADE;
DROP TYPE IF EXISTS notification_channel CASCADE;
DROP TYPE IF EXISTS notification_status CASCADE;
DROP TYPE IF EXISTS notification_trigger CASCADE;
DROP TYPE IF EXISTS tooth_type CASCADE;
DROP TYPE IF EXISTS discount_type CASCADE;
DROP TYPE IF EXISTS log_action CASCADE;

-- ============================================================
-- AppointDent Database Schema (Plain Integer IDs)
-- PostgreSQL (Supabase) | AY 2026-2027
-- ============================================================

-- ============================================================
-- 2. CREATE ENUMS 
-- ============================================================
CREATE TYPE user_role AS ENUM ('superadmin', 'patient', 'staff', 'dentist');
CREATE TYPE appointment_status AS ENUM ('pending','confirmed','rescheduled','completed','cancelled','no_show');
CREATE TYPE payment_method AS ENUM ('gcash','paymaya','credit_card','cash');
CREATE TYPE payment_status AS ENUM ('unpaid','downpaid','paid','refunded');
CREATE TYPE notification_channel AS ENUM ('sms','email');
CREATE TYPE notification_status AS ENUM ('sent','failed','pending');
CREATE TYPE notification_trigger AS ENUM ('confirmation','reschedule','day_before','follow_up','manual');
CREATE TYPE tooth_type AS ENUM ('permanent','temporary');
CREATE TYPE discount_type AS ENUM ('senior','pwd','hmo','philhealth','none');
CREATE TYPE log_action AS ENUM ('created','confirmed','rescheduled','cancelled','completed','no_show','follow_up_set','status_updated');

-- ============================================================
-- 3. USERS & AUTH (MUST REMAIN UUID TO CONNECT TO SUPABASE)
-- ============================================================
CREATE TABLE users (
  id            UUID PRIMARY KEY,
  email         TEXT UNIQUE NOT NULL,
  role          user_role NOT NULL,
  created_at    TIMESTAMPTZ DEFAULT now(),
  updated_at    TIMESTAMPTZ DEFAULT now()
);

-- ============================================================
-- 4. CLINICS (TENANTS) - NOW USING PLAIN NUMBERS
-- ============================================================
CREATE TABLE clinics (
  id                      BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name                    TEXT NOT NULL,
  address                 TEXT NOT NULL,
  latitude                NUMERIC(9,6),
  longitude               NUMERIC(9,6),
  phone                   TEXT,
  email                   TEXT,
  max_appointments_per_day INT DEFAULT 20,
  is_active               BOOLEAN DEFAULT true,
  created_at              TIMESTAMPTZ DEFAULT now(),
  updated_at              TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE clinic_operating_hours (
  id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  clinic_id   BIGINT NOT NULL REFERENCES clinics(id) ON DELETE CASCADE,
  day_of_week SMALLINT NOT NULL CHECK (day_of_week BETWEEN 0 AND 6),
  open_time   TIME NOT NULL,
  close_time  TIME NOT NULL,
  is_closed   BOOLEAN DEFAULT false
);

CREATE TABLE clinic_hmo (
  id        BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  clinic_id BIGINT NOT NULL REFERENCES clinics(id) ON DELETE CASCADE,
  hmo_name  TEXT NOT NULL
);

CREATE TABLE clinic_gallery (
  id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  clinic_id  BIGINT NOT NULL REFERENCES clinics(id) ON DELETE CASCADE,
  image_url  TEXT NOT NULL,
  sort_order SMALLINT DEFAULT 0
);

CREATE TABLE clinic_holidays (
  id             BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  clinic_id      BIGINT NOT NULL REFERENCES clinics(id) ON DELETE CASCADE,
  date           DATE NOT NULL,
  description    TEXT,
  is_special_day BOOLEAN DEFAULT false
);

-- ============================================================
-- 5. STAFF & DENTISTS
-- ============================================================
CREATE TABLE clinic_staff (
  id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id    UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  clinic_id  BIGINT NOT NULL REFERENCES clinics(id) ON DELETE CASCADE,
  first_name TEXT NOT NULL,
  last_name  TEXT NOT NULL,
  UNIQUE(user_id, clinic_id)
);

CREATE TABLE dentists (
  id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id    UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  clinic_id  BIGINT NOT NULL REFERENCES clinics(id) ON DELETE CASCADE,
  first_name TEXT NOT NULL,
  last_name  TEXT NOT NULL,
  specialty  TEXT,
  UNIQUE(user_id, clinic_id)
);

CREATE TABLE dentist_availability (
  id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  dentist_id  BIGINT NOT NULL REFERENCES dentists(id) ON DELETE CASCADE,
  day_of_week SMALLINT NOT NULL CHECK (day_of_week BETWEEN 0 AND 6),
  start_time  TIME NOT NULL,
  end_time    TIME NOT NULL
);

CREATE TABLE dentist_blocked_slots (
  id           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  dentist_id   BIGINT NOT NULL REFERENCES dentists(id) ON DELETE CASCADE,
  blocked_date DATE NOT NULL,
  start_time   TIME,   
  end_time     TIME,
  reason       TEXT
);

-- ============================================================
-- 6. SERVICES & PRODUCTS
-- ============================================================
CREATE TABLE services (
  id                BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  clinic_id         BIGINT NOT NULL REFERENCES clinics(id) ON DELETE CASCADE,
  name              TEXT NOT NULL,
  price             NUMERIC(10,2) NOT NULL,
  slot_duration_min INT NOT NULL DEFAULT 30,
  is_active         BOOLEAN DEFAULT true,
  created_at        TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE products (
  id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  clinic_id  BIGINT NOT NULL REFERENCES clinics(id) ON DELETE CASCADE,
  name       TEXT NOT NULL,
  price      NUMERIC(10,2) NOT NULL,
  is_active  BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ============================================================
-- 7. PATIENTS & MEDICAL HISTORY
-- ============================================================
CREATE TABLE patients (
  id           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id      UUID REFERENCES users(id) ON DELETE SET NULL,
  first_name   TEXT NOT NULL,
  last_name    TEXT NOT NULL,
  phone        TEXT NOT NULL,  
  birthdate    DATE,            
  gender       TEXT,
  address      TEXT,
  is_guest     BOOLEAN DEFAULT false,
  created_at   TIMESTAMPTZ DEFAULT now(),
  updated_at   TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE informed_consent (
  id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  patient_id  BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  accepted_at TIMESTAMPTZ DEFAULT now(),
  ip_address  TEXT,
  UNIQUE(patient_id)
);

CREATE TABLE patient_medical_history (
  id                  BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  patient_id          BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  blood_type          TEXT,
  allergies           TEXT[],
  current_medications TEXT[],
  medical_conditions  TEXT[],
  previous_surgeries  TEXT,
  is_pregnant         BOOLEAN,
  is_smoker           BOOLEAN,
  updated_at          TIMESTAMPTZ DEFAULT now(),
  UNIQUE(patient_id)
);

-- ============================================================
-- 8. APPOINTMENTS & LOGS
-- ============================================================
CREATE TABLE appointments (
  id               BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  patient_id       BIGINT NOT NULL REFERENCES patients(id),
  clinic_id        BIGINT NOT NULL REFERENCES clinics(id),
  dentist_id       BIGINT NOT NULL REFERENCES dentists(id),
  service_id       BIGINT REFERENCES services(id),
  status           appointment_status NOT NULL DEFAULT 'pending',
  scheduled_at     TIMESTAMPTZ NOT NULL,
  end_at           TIMESTAMPTZ NOT NULL,
  notes            TEXT,
  is_walk_in       BOOLEAN DEFAULT false,
  downpayment      NUMERIC(10,2) DEFAULT 0,
  payment_method   payment_method,
  payment_status   payment_status DEFAULT 'unpaid',
  created_at       TIMESTAMPTZ DEFAULT now(),
  updated_at       TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_appointments_clinic_date ON appointments(clinic_id, scheduled_at);
CREATE INDEX idx_appointments_dentist_date ON appointments(dentist_id, scheduled_at);
CREATE INDEX idx_appointments_patient ON appointments(patient_id);

CREATE TABLE appointment_logs (
  id             BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  appointment_id BIGINT NOT NULL REFERENCES appointments(id) ON DELETE CASCADE,
  performed_by   UUID REFERENCES users(id),
  role           user_role,
  action         log_action NOT NULL,
  old_status     appointment_status,
  new_status     appointment_status,
  notes          TEXT,
  created_at     TIMESTAMPTZ DEFAULT now()
);

-- ============================================================
-- 9. CLINICAL RECORDS
-- ============================================================
CREATE TABLE dental_charts (
  id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  patient_id BIGINT NOT NULL REFERENCES patients(id),
  clinic_id  BIGINT NOT NULL REFERENCES clinics(id),
  dentist_id BIGINT NOT NULL REFERENCES dentists(id),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE tooth_conditions (
  id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  dental_chart_id BIGINT NOT NULL REFERENCES dental_charts(id) ON DELETE CASCADE,
  tooth_number    SMALLINT NOT NULL CHECK (tooth_number BETWEEN 1 AND 52),
  tooth_type      tooth_type NOT NULL,
  condition       TEXT NOT NULL, 
  surface         TEXT,          
  notes           TEXT,
  recorded_at     TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE periodontal_screenings (
  id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  patient_id      BIGINT NOT NULL REFERENCES patients(id),
  clinic_id       BIGINT NOT NULL REFERENCES clinics(id),
  dentist_id      BIGINT NOT NULL REFERENCES dentists(id),
  appointment_id  BIGINT REFERENCES appointments(id),
  pocket_depths   JSONB,  
  bleeding_points JSONB,
  findings        TEXT,
  screened_at     TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE tmj_assessments (
  id             BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  patient_id     BIGINT NOT NULL REFERENCES patients(id),
  clinic_id      BIGINT NOT NULL REFERENCES clinics(id),
  dentist_id     BIGINT NOT NULL REFERENCES dentists(id),
  appointment_id BIGINT REFERENCES appointments(id),
  findings       TEXT,
  pain_scale     SMALLINT CHECK (pain_scale BETWEEN 0 AND 10),
  assessed_at    TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE oral_surgery_records (
  id             BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  patient_id     BIGINT NOT NULL REFERENCES patients(id),
  clinic_id      BIGINT NOT NULL REFERENCES clinics(id),
  dentist_id     BIGINT NOT NULL REFERENCES dentists(id),
  appointment_id BIGINT REFERENCES appointments(id),
  procedure_name TEXT NOT NULL,
  tooth_number   SMALLINT,
  anesthesia     TEXT,
  notes          TEXT,
  performed_at   TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE prescriptions (
  id             BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  patient_id     BIGINT NOT NULL REFERENCES patients(id),
  clinic_id      BIGINT NOT NULL REFERENCES clinics(id),
  dentist_id     BIGINT NOT NULL REFERENCES dentists(id),
  appointment_id BIGINT REFERENCES appointments(id),
  medication     TEXT NOT NULL,
  dosage         TEXT NOT NULL,
  frequency      TEXT NOT NULL,
  duration       TEXT,
  notes          TEXT,
  prescribed_at  TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE clinical_assessments (
  id             BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  patient_id     BIGINT NOT NULL REFERENCES patients(id),
  clinic_id      BIGINT NOT NULL REFERENCES clinics(id),
  dentist_id     BIGINT NOT NULL REFERENCES dentists(id),
  appointment_id BIGINT REFERENCES appointments(id),
  chief_complaint TEXT,
  diagnosis       TEXT NOT NULL,
  treatment_plan  TEXT,
  notes           TEXT,
  assessed_at     TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE treatment_history (
  id             BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  patient_id     BIGINT NOT NULL REFERENCES patients(id),
  clinic_id      BIGINT NOT NULL REFERENCES clinics(id),
  dentist_id     BIGINT NOT NULL REFERENCES dentists(id),
  appointment_id BIGINT REFERENCES appointments(id),
  service_id     BIGINT REFERENCES services(id),
  treatment      TEXT NOT NULL,
  tooth_number   SMALLINT,
  notes          TEXT,
  performed_at   TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE follow_up_schedules (
  id             BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  patient_id     BIGINT NOT NULL REFERENCES patients(id),
  clinic_id      BIGINT NOT NULL REFERENCES clinics(id),
  dentist_id     BIGINT NOT NULL REFERENCES dentists(id),
  appointment_id BIGINT REFERENCES appointments(id), 
  scheduled_at   TIMESTAMPTZ NOT NULL,
  reason         TEXT,
  is_completed   BOOLEAN DEFAULT false,
  created_at     TIMESTAMPTZ DEFAULT now()
);

-- ============================================================
-- 10. BILLING & INVENTORY
-- ============================================================
CREATE TABLE transactions (
  id                  BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  appointment_id      BIGINT NOT NULL REFERENCES appointments(id),
  patient_id          BIGINT NOT NULL REFERENCES patients(id),
  clinic_id           BIGINT NOT NULL REFERENCES clinics(id),
  subtotal            NUMERIC(10,2) NOT NULL,
  discount_type       discount_type DEFAULT 'none',
  discount_amount     NUMERIC(10,2) DEFAULT 0,
  hmo_coverage        NUMERIC(10,2) DEFAULT 0,
  philhealth_coverage NUMERIC(10,2) DEFAULT 0,
  total_amount        NUMERIC(10,2) NOT NULL,
  payment_method      payment_method,
  payment_status      payment_status DEFAULT 'unpaid',
  created_at          TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE transaction_items (
  id             BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  transaction_id BIGINT NOT NULL REFERENCES transactions(id) ON DELETE CASCADE,
  service_id     BIGINT REFERENCES services(id),
  product_id     BIGINT REFERENCES products(id),
  description    TEXT NOT NULL,
  quantity       INT NOT NULL DEFAULT 1,
  unit_price     NUMERIC(10,2) NOT NULL,
  total_price    NUMERIC(10,2) NOT NULL
);

CREATE TABLE inventory_items (
  id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  clinic_id       BIGINT NOT NULL REFERENCES clinics(id) ON DELETE CASCADE,
  name            TEXT NOT NULL,
  unit            TEXT NOT NULL,
  quantity        NUMERIC(10,2) NOT NULL DEFAULT 0,
  alert_threshold NUMERIC(10,2) NOT NULL DEFAULT 5,
  created_at      TIMESTAMPTZ DEFAULT now(),
  updated_at      TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE inventory_logs (
  id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  item_id    BIGINT NOT NULL REFERENCES inventory_items(id) ON DELETE CASCADE,
  changed_by UUID REFERENCES users(id),
  delta      NUMERIC(10,2) NOT NULL, 
  reason     TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ============================================================
-- 11. NOTIFICATIONS & FEEDBACK
-- ============================================================
CREATE TABLE notifications (
  id             BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  appointment_id BIGINT REFERENCES appointments(id),
  patient_id     BIGINT NOT NULL REFERENCES patients(id),
  trigger_type   notification_trigger NOT NULL,
  channel        notification_channel NOT NULL,
  status         notification_status DEFAULT 'pending',
  error_message  TEXT,
  sent_at        TIMESTAMPTZ,
  created_at     TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE feedback (
  id             BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  patient_id     BIGINT NOT NULL REFERENCES patients(id),
  clinic_id      BIGINT NOT NULL REFERENCES clinics(id),
  appointment_id BIGINT NOT NULL REFERENCES appointments(id),
  rating         SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment        TEXT,
  created_at     TIMESTAMPTZ DEFAULT now(),
  UNIQUE(patient_id, appointment_id)
);

-- ============================================================
-- 12. ROW LEVEL SECURITY RULES (WITH SUPERADMIN BYPASS)
-- ============================================================

ALTER TABLE users                  ENABLE ROW LEVEL SECURITY;
ALTER TABLE clinics                ENABLE ROW LEVEL SECURITY;
ALTER TABLE clinic_operating_hours ENABLE ROW LEVEL SECURITY;
ALTER TABLE clinic_hmo             ENABLE ROW LEVEL SECURITY;
ALTER TABLE clinic_gallery         ENABLE ROW LEVEL SECURITY;
ALTER TABLE clinic_holidays        ENABLE ROW LEVEL SECURITY;
ALTER TABLE clinic_staff           ENABLE ROW LEVEL SECURITY;
ALTER TABLE dentists               ENABLE ROW LEVEL SECURITY;
ALTER TABLE dentist_availability   ENABLE ROW LEVEL SECURITY;
ALTER TABLE dentist_blocked_slots  ENABLE ROW LEVEL SECURITY;
ALTER TABLE services               ENABLE ROW LEVEL SECURITY;
ALTER TABLE products               ENABLE ROW LEVEL SECURITY;
ALTER TABLE patients               ENABLE ROW LEVEL SECURITY;
ALTER TABLE informed_consent       ENABLE ROW LEVEL SECURITY;
ALTER TABLE patient_medical_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE appointments           ENABLE ROW LEVEL SECURITY;
ALTER TABLE appointment_logs       ENABLE ROW LEVEL SECURITY;
ALTER TABLE dental_charts          ENABLE ROW LEVEL SECURITY;
ALTER TABLE tooth_conditions       ENABLE ROW LEVEL SECURITY;
ALTER TABLE periodontal_screenings ENABLE ROW LEVEL SECURITY;
ALTER TABLE tmj_assessments        ENABLE ROW LEVEL SECURITY;
ALTER TABLE oral_surgery_records   ENABLE ROW LEVEL SECURITY;
ALTER TABLE prescriptions          ENABLE ROW LEVEL SECURITY;
ALTER TABLE clinical_assessments   ENABLE ROW LEVEL SECURITY;
ALTER TABLE treatment_history      ENABLE ROW LEVEL SECURITY;
ALTER TABLE follow_up_schedules    ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions           ENABLE ROW LEVEL SECURITY;
ALTER TABLE transaction_items      ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_items        ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_logs         ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications          ENABLE ROW LEVEL SECURITY;
ALTER TABLE feedback               ENABLE ROW LEVEL SECURITY;

-- 12A. Helper Functions (Updated to return BIGINT for Clinic IDs)
CREATE OR REPLACE FUNCTION auth_role() RETURNS user_role AS $$
  SELECT (auth.jwt() ->> 'role')::user_role;
$$ LANGUAGE sql STABLE;

CREATE OR REPLACE FUNCTION auth_clinic_id() RETURNS BIGINT AS $$
  SELECT clinic_id FROM clinic_staff WHERE user_id = auth.uid()
  UNION
  SELECT clinic_id FROM dentists WHERE user_id = auth.uid()
  LIMIT 1;
$$ LANGUAGE sql STABLE;

-- 12B. RLS Policies
CREATE POLICY user_access_self ON users
  FOR ALL USING (id = auth.uid() OR auth_role() = 'superadmin');

CREATE POLICY clinics_public_browse ON clinics
  FOR SELECT USING (is_active = true OR auth_role() = 'superadmin');

CREATE POLICY clinics_superadmin_manage ON clinics
  FOR ALL USING (auth_role() = 'superadmin');

CREATE POLICY patient_self ON patients
  USING (user_id = auth.uid() OR auth_role() IN ('staff','dentist','superadmin'));

CREATE POLICY medical_history_policy ON patient_medical_history
  USING (
    patient_id IN (SELECT id FROM patients WHERE user_id = auth.uid())
    OR auth_role() IN ('staff','dentist','superadmin')
  );

CREATE POLICY appt_patient ON appointments
  FOR SELECT USING (
    patient_id IN (SELECT id FROM patients WHERE user_id = auth.uid())
    OR clinic_id = auth_clinic_id()
    OR auth_role() = 'superadmin'
  );

CREATE POLICY appt_staff_write ON appointments
  FOR ALL USING (
    (auth_role() = 'staff' AND clinic_id = auth_clinic_id()) 
    OR auth_role() = 'superadmin'
  );

CREATE POLICY appt_log_insert ON appointment_logs FOR INSERT
  WITH CHECK (auth_role() IN ('staff','dentist','superadmin'));

CREATE POLICY appt_log_select ON appointment_logs FOR SELECT
  USING (auth_role() IN ('staff','dentist','superadmin'));

CREATE POLICY feedback_read ON feedback
  FOR SELECT USING (
    patient_id IN (SELECT id FROM patients WHERE user_id = auth.uid())
    OR (auth_role() = 'staff' AND clinic_id = auth_clinic_id())
    OR auth_role() = 'superadmin'
  );