create table if not exists public.clinic_patients (
  id bigint generated by default as identity primary key,
  clinic_id integer not null references public.clinics(id) on delete cascade,
  patient_id bigint not null references public.patients(id) on delete cascade,
  enrolled_by uuid references public.users(id) on delete set null,
  is_active boolean not null default true,
  created_at timestamptz default now(),
  unique (clinic_id, patient_id)
);

alter table public.clinic_patients enable row level security;

drop policy if exists "clinic_patients_select" on public.clinic_patients;
drop policy if exists "clinic_patients_insert" on public.clinic_patients;
drop policy if exists "clinic_patients_update" on public.clinic_patients;

create policy "clinic_patients_select" on public.clinic_patients
  for select to authenticated using (
    (select role from public.users where id = auth.uid()) in ('staff', 'dentist', 'superadmin')
  );

create policy "clinic_patients_insert" on public.clinic_patients
  for insert to authenticated
  with check (
    (select role from public.users where id = auth.uid()) in ('staff', 'dentist', 'superadmin')
  );

create policy "clinic_patients_update" on public.clinic_patients
  for update to authenticated
  using (
    (select role from public.users where id = auth.uid()) in ('staff', 'dentist', 'superadmin')
  );

-- Backfill: pull existing patient-clinic relationships from appointments
insert into public.clinic_patients (clinic_id, patient_id)
select distinct clinic_id, patient_id
from public.appointments
where clinic_id is not null and patient_id is not null
on conflict (clinic_id, patient_id) do nothing;
