create table public.patient_documents (
  id bigint generated by default as identity primary key,
  patient_id bigint not null references public.patients(id) on delete cascade,
  clinic_id bigint references public.clinics(id),
  uploaded_by uuid references public.users(id),
  uploaded_by_name text not null,
  uploaded_by_branch text not null,
  section text not null check (section in ('medical_records','xrays','consent_forms','treatment_photos','other')),
  file_name text not null,
  file_path text not null,
  file_type text not null check (file_type in ('image','pdf')),
  mime_type text not null,
  size_bytes bigint not null,
  created_at timestamptz not null default now()
);

alter table public.patient_documents enable row level security;

create policy "patient_documents_select" on public.patient_documents
  for select to authenticated
  using ((select users.role from users where users.id = auth.uid()) = any (array['staff'::user_role, 'dentist'::user_role, 'superadmin'::user_role]));

create policy "patient_documents_patient_read" on public.patient_documents
  for select
  using (patient_id in (select patients.id from patients where patients.user_id = auth.uid()));

create policy "patient_documents_insert" on public.patient_documents
  for insert to authenticated
  with check ((select users.role from users where users.id = auth.uid()) = any (array['dentist'::user_role, 'staff'::user_role, 'superadmin'::user_role]));

create policy "patient_documents_delete" on public.patient_documents
  for delete to authenticated
  using ((select users.role from users where users.id = auth.uid()) = 'superadmin'::user_role);
