create table if not exists public.inventory_categories (
  id bigint generated by default as identity primary key,
  clinic_id integer not null references public.clinics(id) on delete cascade,
  name text not null,
  created_at timestamptz default now(),
  unique (clinic_id, name)
);

alter table public.inventory_items
  add column if not exists category_id bigint references public.inventory_categories(id) on delete set null;

alter table public.inventory_items
  add column if not exists expiry_date date;

alter table public.inventory_categories enable row level security;

drop policy if exists "inventory_categories_select" on public.inventory_categories;
drop policy if exists "inventory_categories_insert" on public.inventory_categories;
drop policy if exists "inventory_categories_update" on public.inventory_categories;
drop policy if exists "inventory_categories_delete" on public.inventory_categories;

create policy "inventory_categories_select" on public.inventory_categories
  for select to authenticated using (
    (select role from public.users where id = auth.uid()) in ('staff', 'dentist', 'superadmin')
  );

create policy "inventory_categories_insert" on public.inventory_categories
  for insert to authenticated
  with check (
    (select role from public.users where id = auth.uid()) in ('staff', 'superadmin')
  );

create policy "inventory_categories_update" on public.inventory_categories
  for update to authenticated
  using (
    (select role from public.users where id = auth.uid()) in ('staff', 'superadmin')
  );

create policy "inventory_categories_delete" on public.inventory_categories
  for delete to authenticated
  using (
    (select role from public.users where id = auth.uid()) in ('staff', 'superadmin')
  );
