create table public.periodontal_findings (
  id bigint generated by default as identity primary key,
  patient_id bigint not null references public.patients(id) on delete cascade,
  clinic_id bigint not null references public.clinics(id),
  dentist_id bigint not null references public.dentists(id),
  appointment_id bigint references public.appointments(id),
  dental_chart_id bigint references public.dental_charts(id),
  gingivitis jsonb not null default '[]'::jsonb,
  periodontal_condition jsonb not null default '[]'::jsonb,
  occlusion jsonb not null default '[]'::jsonb,
  appliances jsonb not null default '[]'::jsonb,
  recorded_at timestamptz not null default now(),
  created_at timestamptz default now()
);

alter table public.periodontal_findings enable row level security;

create policy "findings_staff_access" on public.periodontal_findings
  for all
  using (((auth_role() = any (array['staff'::text, 'dentist'::text])) and (clinic_id = auth_clinic_id())) or (auth_role() = 'superadmin'::text))
  with check (((auth_role() = any (array['staff'::text, 'dentist'::text])) and (clinic_id = auth_clinic_id())) or (auth_role() = 'superadmin'::text));

create policy "periodontal_findings_delete" on public.periodontal_findings
  for delete to authenticated
  using ((select users.role from users where users.id = auth.uid()) = 'superadmin'::user_role);

create policy "periodontal_findings_insert" on public.periodontal_findings
  for insert to authenticated
  with check ((select users.role from users where users.id = auth.uid()) = any (array['dentist'::user_role, 'superadmin'::user_role]));

create policy "periodontal_findings_select" on public.periodontal_findings
  for select to authenticated
  using ((select users.role from users where users.id = auth.uid()) = any (array['staff'::user_role, 'dentist'::user_role, 'superadmin'::user_role]));

create policy "periodontal_findings_update" on public.periodontal_findings
  for update to authenticated
  using ((select users.role from users where users.id = auth.uid()) = any (array['dentist'::user_role, 'superadmin'::user_role]));

create policy "findings_patient_read" on public.periodontal_findings
  for select
  using (patient_id in (select patients.id from patients where patients.user_id = auth.uid()));
